export interface SampleWordTiming {
  word: string;
  startMs: number;
  endMs: number;
}

export interface SamplePostcard {
  id: string;
  title: string;
  location: string;
  language: string;
  frontImage: any;
  backImage: any;
  originalText?: string;
  translatedText?: string;
  detectedLanguage?: string;
  description?: string;
  words?: string[];
  audioAsset?: any;
  durationMs?: number;
  wordTimings?: SampleWordTiming[];
}

const parisTimings: SampleWordTiming[] = [
  { word: "Dear", startMs: 0, endMs: 267 },
  { word: "Marie,", startMs: 325, endMs: 987 },
  { word: "Paris", startMs: 1196, endMs: 1649 },
  { word: "is", startMs: 1718, endMs: 1800 },
  { word: "magnificent!", startMs: 1881, endMs: 2868 },
  { word: "The", startMs: 3564, endMs: 3692 },
  { word: "croissants", startMs: 3750, endMs: 4331 },
  { word: "are", startMs: 4377, endMs: 4516 },
  { word: "delicious", startMs: 4551, endMs: 5201 },
  { word: "and", startMs: 5526, endMs: 5712 },
  { word: "the", startMs: 5747, endMs: 5852 },
  { word: "Eiffel", startMs: 5910, endMs: 6225 },
  { word: "Tower", startMs: 6260, endMs: 6516 },
  { word: "shines", startMs: 6551, endMs: 6935 },
  { word: "every", startMs: 6993, endMs: 7238 },
  { word: "night.", startMs: 7296, endMs: 7819 },
  { word: "I", startMs: 8445, endMs: 8503 },
  { word: "think", startMs: 8538, endMs: 8760 },
  { word: "of", startMs: 8795, endMs: 8876 },
  { word: "you.", startMs: 8935, endMs: 9377 },
  { word: "Kisses,", startMs: 10023, endMs: 10568 },
  { word: "Sophie.", startMs: 10626, endMs: 11993 },
];

const tokyoTimings: SampleWordTiming[] = [
  { word: "Dear", startMs: 0, endMs: 290 },
  { word: "Mom,", startMs: 348, endMs: 870 },
  { word: "Tokyo", startMs: 1070, endMs: 1580 },
  { word: "is", startMs: 1640, endMs: 1730 },
  { word: "so", startMs: 1790, endMs: 1920 },
  { word: "beautiful.", startMs: 1980, endMs: 2850 },
  { word: "The", startMs: 3450, endMs: 3580 },
  { word: "cherry", startMs: 3640, endMs: 4020 },
  { word: "blossoms", startMs: 4080, endMs: 4650 },
  { word: "are", startMs: 4710, endMs: 4850 },
  { word: "in", startMs: 4910, endMs: 4990 },
  { word: "full", startMs: 5050, endMs: 5260 },
  { word: "bloom,", startMs: 5320, endMs: 5890 },
  { word: "and", startMs: 6100, endMs: 6280 },
  { word: "every", startMs: 6340, endMs: 6620 },
  { word: "day", startMs: 6680, endMs: 6870 },
  { word: "brings", startMs: 6930, endMs: 7240 },
  { word: "new", startMs: 7300, endMs: 7480 },
  { word: "discoveries.", startMs: 7540, endMs: 8560 },
  { word: "The", startMs: 9150, endMs: 9280 },
  { word: "sushi", startMs: 9340, endMs: 9730 },
  { word: "is", startMs: 9790, endMs: 9880 },
  { word: "the", startMs: 9940, endMs: 10050 },
  { word: "best!", startMs: 10110, endMs: 10680 },
  { word: "With", startMs: 11200, endMs: 11440 },
  { word: "love,", startMs: 11500, endMs: 11900 },
  { word: "Kenta.", startMs: 11960, endMs: 13299 },
];

const santoriniTimings: SampleWordTiming[] = [
  { word: "Dear", startMs: 0, endMs: 280 },
  { word: "Dad,", startMs: 340, endMs: 880 },
  { word: "Santorini", startMs: 1080, endMs: 1820 },
  { word: "is", startMs: 1880, endMs: 1970 },
  { word: "a", startMs: 2030, endMs: 2090 },
  { word: "dream!", startMs: 2150, endMs: 2850 },
  { word: "The", startMs: 3450, endMs: 3580 },
  { word: "sea", startMs: 3640, endMs: 3900 },
  { word: "is", startMs: 3960, endMs: 4050 },
  { word: "so", startMs: 4110, endMs: 4250 },
  { word: "blue", startMs: 4310, endMs: 4650 },
  { word: "and", startMs: 4710, endMs: 4890 },
  { word: "the", startMs: 4950, endMs: 5060 },
  { word: "sunsets", startMs: 5120, endMs: 5620 },
  { word: "are", startMs: 5680, endMs: 5820 },
  { word: "breathtaking.", startMs: 5880, endMs: 6880 },
  { word: "I", startMs: 7480, endMs: 7540 },
  { word: "wish", startMs: 7600, endMs: 7850 },
  { word: "you", startMs: 7910, endMs: 8020 },
  { word: "were", startMs: 8080, endMs: 8280 },
  { word: "here.", startMs: 8340, endMs: 8920 },
  { word: "Many", startMs: 9520, endMs: 9780 },
  { word: "greetings,", startMs: 9840, endMs: 10520 },
  { word: "Anna.", startMs: 10580, endMs: 12228 },
];

const scoutsTimings: SampleWordTiming[] = [
  { word: "Who", startMs: 0, endMs: 197 },
  { word: "calls", startMs: 267, endMs: 557 },
  { word: "upon", startMs: 604, endMs: 836 },
  { word: "you", startMs: 906, endMs: 987 },
  { word: "Greetings:", startMs: 1068, endMs: 1939 },
  { word: "Hein;", startMs: 2635, endMs: 3239 },
  { word: "Irmtraud;", startMs: 3750, endMs: 4644 },
  { word: "Gregor;", startMs: 5341, endMs: 6049 },
  { word: "Günther;", startMs: 6745, endMs: 7430 },
  { word: "Richard;", startMs: 8127, endMs: 8824 },
  { word: ";", startMs: 8870, endMs: 8905 },
  { word: "Hermann;", startMs: 9601, endMs: 10298 },
  { word: "Bütger;", startMs: 10995, endMs: 11691 },
  { word: "Rudolf;", startMs: 12388, endMs: 13131 },
  { word: ";", startMs: 13514, endMs: 13537 },
  { word: "Grumbach;", startMs: 13978, endMs: 14791 },
  { word: "Alfons;", startMs: 15488, endMs: 16393 },
  { word: "Hanny;", startMs: 16997, endMs: 17833 }
];

const deerTimings: SampleWordTiming[] = [
  { word: "In", startMs: 0, endMs: 151 },
  { word: "remembrance", startMs: 232, endMs: 824 },
  { word: "of", startMs: 871, endMs: 952 },
  { word: "holidays", startMs: 1045, endMs: 1672 },
  { word: "1934.", startMs: 2276, endMs: 3553 },
  { word: "Gertrud", startMs: 4249, endMs: 4853 },
  { word: "Mantiberg", startMs: 4969, endMs: 5747 },
  { word: "June", startMs: 6699, endMs: 7117 },
  { word: "6,", startMs: 7187, endMs: 7755 },
  { word: "1934.", startMs: 7837, endMs: 9381 }
];

export const samplePostcards: SamplePostcard[] = [
  {
    id: "sample-paris",
    title: "Paris, France",
    location: "Paris",
    language: "French",
    frontImage: require("@/assets/samples/paris_front.png"),
    backImage: require("@/assets/samples/paris_back.png"),
    originalText: "Chère Marie, Paris est magnifique! Les croissants sont délicieux et la Tour Eiffel brille chaque nuit. Je pense à toi. Bisous, Sophie.",
    translatedText: "Dear Marie, Paris is magnificent! The croissants are delicious and the Eiffel Tower shines every night. I think of you. Kisses, Sophie.",
    detectedLanguage: "French",
    description: "A scenic view of the Eiffel Tower in Paris at sunset, with the sun illuminating the city and the River Seine flowing through the cityscape.",
    words: ["Dear", "Marie,", "Paris", "is", "magnificent!", "The", "croissants", "are", "delicious", "and", "the", "Eiffel", "Tower", "shines", "every", "night.", "I", "think", "of", "you.", "Kisses,", "Sophie."],
    audioAsset: require("@/assets/samples/paris_audio.mp3"),
    durationMs: 11993,
    wordTimings: parisTimings,
  },
  {
    id: "sample-tokyo",
    title: "Tokyo, Japan",
    location: "Tokyo",
    language: "Japanese",
    frontImage: require("@/assets/samples/tokyo_front.png"),
    backImage: require("@/assets/samples/tokyo_back.png"),
    originalText: "親愛なるお母さん、東京はとても美しいです。桜が満開で、毎日新しい発見があります。お寿司が最高です！愛を込めて、健太",
    translatedText: "Dear Mom, Tokyo is so beautiful. The cherry blossoms are in full bloom, and every day brings new discoveries. The sushi is the best! With love, Kenta.",
    detectedLanguage: "Japanese",
    description: "A traditional Japanese pagoda framed by lush pink cherry blossom trees, with the snow-capped peak of Mount Fuji rising majestically in the background under a clear blue sky.",
    words: ["Dear", "Mom,", "Tokyo", "is", "so", "beautiful.", "The", "cherry", "blossoms", "are", "in", "full", "bloom,", "and", "every", "day", "brings", "new", "discoveries.", "The", "sushi", "is", "the", "best!", "With", "love,", "Kenta."],
    audioAsset: require("@/assets/samples/tokyo_audio.mp3"),
    durationMs: 13299,
    wordTimings: tokyoTimings,
  },
  {
    id: "sample-santorini",
    title: "Santorini, Greece",
    location: "Santorini",
    language: "German",
    frontImage: require("@/assets/samples/santorini_front.png"),
    backImage: require("@/assets/samples/santorini_back.png"),
    originalText: "Lieber Papa, Santorini ist ein Traum! Das Meer ist so blau und die Sonnenuntergänge sind atemberaubend. Ich wünschte du wärst hier. Viele Grüße, Anna.",
    translatedText: "Dear Dad, Santorini is a dream! The sea is so blue and the sunsets are breathtaking. I wish you were here. Many greetings, Anna.",
    detectedLanguage: "German",
    description: "Whitewashed buildings with distinctive blue domes perched on a cliffside in Santorini, overlooking the deep blue caldera with rocky islands visible in the distance.",
    words: ["Dear", "Dad,", "Santorini", "is", "a", "dream!", "The", "sea", "is", "so", "blue", "and", "the", "sunsets", "are", "breathtaking.", "I", "wish", "you", "were", "here.", "Many", "greetings,", "Anna."],
    audioAsset: require("@/assets/samples/santorini_audio.mp3"),
    durationMs: 12228,
    wordTimings: santoriniTimings,
  },
  {
    id: "sample-christmas",
    title: "Christmas Card",
    location: "Dresden",
    language: "German",
    frontImage: require("@/assets/samples/christmas_front.jpg"),
    backImage: require("@/assets/samples/christmas_back.jpg"),
    originalText: "Frohe\nWeihnachten\nund viel\nGlück\nim neuen\nJahr\n\nDresden, d. 12.12.82\nwünschen Dir liebe Bübi,\nsowie Deiner Familie aus\nder fernen Heimat Dein alter\nFreund\nErich u. Gattin.\n\nUns geht es den Umständen ent.\nsprechend noch halbwegs gut.\nGesundheitlich könnte es mir besser\ngehen, ich habe sehr unter hohen\nBlutdruck zu leiden. Wir gehen ja\nnun auf die 60 zu, und da muß man\nmit solchen weh - Wehchen eben\nrechnen. Wie geht es Dir lieber\nBübi, bist du wenigstens noch bei\nbester Gesundheit oder haben bei\nDir auch schon die Generalrepara-\nturen begonnen. Wenn du Zeit\nhast schreibe mir bitte auch wieder\nmal paar Zeilen, ich würde mich sehr\ndarüber freuen. Oder hast du gar vor\nDresden wieder mal zu besuchen??\nNochmals herzliche Grüße von Deinen alten Freunden\nErich.",
    translatedText: "Happy\nChristmas\nand much\nluck\nin the new\nyear\n\nDresden, Dec. 12, 1982\nYour old friend Erich and wife send wishes to you, dear Bübi, and your family from the distant homeland.\n\nWe are, considering the circumstances, still halfway well. Health-wise, it could be better; I suffer greatly from high blood pressure. We are approaching 60 now, and one has to expect such aches and pains. How are you, dear Bübi? Are you at least still in best health, or have the general repairs already begun for you too? If you have time, please write me a few lines again; I would be very happy about it. Or do you even plan to visit Dresden again??\nWarmest regards again from your old friends\nErich.",
    detectedLanguage: "de",
    description: "The postcard consists of two sides. One side features a pre-printed holiday greeting in German (\"Frohe Weihnachten und viel Glück im neuen Jahr\") in an old German (Fraktur) script, centered on a plain white background. The other side contains a handwritten personal message in German, dated \"Dresden, d. 12.12.82\", on a plain, light-colored paper background. There is no specific imagery or artwork visible on either side beyond the text itself.",
    words: ["Happy", "Christmas", "and", "much", "luck", "in", "the", "new", "year", "Dresden", "Dec.", "12", "1982", "Your", "old", "friend", "Erich", "and", "wife", "send", "wishes", "to", "you", "dear", "Bübi", "and", "your", "family", "from", "the", "distant", "homeland", "We", "are", "considering", "the", "circumstances", "still", "halfway", "well", "Health-wise", "it", "could", "be", "better", "I", "suffer", "greatly", "from", "high", "blood", "pressure", "We", "are", "approaching", "60", "now", "and", "one", "has", "to", "expect", "such", "aches", "and", "pains", "How", "are", "you", "dear", "Bübi", "Are", "you", "at", "least", "still", "in", "best", "health", "or", "have", "the", "general", "repairs", "already", "begun", "for", "you", "too", "If", "you", "have", "time", "please", "write", "me", "a", "few", "lines", "again", "I", "would", "be", "very", "happy", "about", "it", "Or", "do", "you", "even", "plan", "to", "visit", "Dresden", "again", "Warmest", "regards", "again", "from", "your", "old", "friends", "Erich"],
  },
  {
    id: "sample-dresden-bw",
    title: "Dresden Views",
    location: "Dresden",
    language: "German",
    frontImage: require("@/assets/samples/dresden_bw_front.jpg"),
    backImage: require("@/assets/samples/dresden_bw_back.jpg"),
    originalText: "1 Kronentor des Zwingers\n2 Blick zum Terrassen ufer\n3 „Goldener Reiter“\n4 Prager Straße\n5 Dr.-Friedrichs-Brücke\n6 Blick zum Rathaus und zur Kreuzkirche\n\nLieber Bubi u. Familie!\nEntschuldige bitte die Verspätung des Oster- u. Neuj. Grüße aus Dresden. Alf\nBei uns war es vor u. bei allen den Feiertagen die Handwerker so daß vieles nicht geworden ist. Uns geht es ganz gut, jedes Jahr wird wieder etwas neues geschaffen. Hauptsache wir bleiben alle gesund, dass ich auch von Euch hoffe.\nViele Grüße aus dem schönen\nDresden. Alfred u. Foren\nKönnt Du mal wieder?",
    translatedText: "1 Crown Gate of the Zwinger\n2 View to the Terrace Embankment\n3 \"Golden Rider\"\n4 Prager Street\n5 Dr.-Friedrichs Bridge\n6 View to the City Hall and the Kreuzkirche\n\nDear Bubi and Family!\nPlease excuse the delay for Easter and New Year's greetings from Dresden. Alf\nWith us, before and during all the holidays, the craftsmen were around, so that much could not be done. We are doing quite well, every year something new is created again. The main thing is that we all stay healthy, which I also hope for you.\nMany greetings from beautiful\nDresden. Alfred and Foren\nCan you visit again?",
    detectedLanguage: "de",
    description: "The postcard features a collage of six black-and-white photographs of famous landmarks and cityscapes in Dresden, Germany. These include the Kronentor of the Zwinger palace, a view of the Elbe River's terrace embankment, the \"Golden Rider\" statue, a street scene of Prager Straße, an aerial view of the Dr.-Friedrichs Bridge, and a panorama showing the City Hall and Kreuzkirche. A central banner reads \"Grüße aus Dresden\" (Greetings from Dresden).",
    words: ["1", "Crown", "Gate", "of", "the", "Zwinger", "2", "View", "to", "the", "Terrace", "Embankment", "3", "\"Golden", "Rider\"", "4", "Prager", "Street", "5", "Dr.-Friedrichs", "Bridge", "6", "View", "to", "the", "City", "Hall", "and", "the", "Kreuzkirche", "Dear", "Bubi", "and", "Family!", "Please", "excuse", "the", "delay", "for", "Easter", "and", "New", "Year's", "greetings", "from", "Dresden.", "Alf", "With", "us,", "before", "and", "during", "all", "the", "holidays,", "the", "craftsmen", "were", "around,", "so", "that", "much", "could", "not", "be", "done.", "We", "are", "doing", "quite", "well,", "every", "year", "something", "new", "is", "created", "again.", "The", "main", "thing", "is", "that", "we", "all", "stay", "healthy,", "which", "I", "also", "hope", "for", "you.", "Many", "greetings", "from", "beautiful", "Dresden.", "Alfred", "and", "Foren", "Can", "you", "visit", "again?"],
  },
  {
    id: "sample-dresden-color",
    title: "Dresden to Caribbean",
    location: "Dresden",
    language: "German",
    frontImage: require("@/assets/samples/dresden_color_front.jpg"),
    backImage: require("@/assets/samples/dresden_color_back.jpg"),
    originalText: "12. 5. 72\nLieber Bubu u Familie.\nWarum schreibst Du gar nicht mal. Habe\nmeine Post alle von Santo\nDomingo wieder zurück\nbekommen. Hast Du eine\nneue Adresse? Dein Paket\nvon jener haben mir nicht\nmehr erhalten. Habe Dir\npaarmal geschrieben schon\nschreiben Dich auch mal bitter\nkurz. Es grüßt Dich herzlich\nDeiner Richard u Frank.",
    translatedText: "May 12, 1972\nDear Bubu and family.\nWhy don't you ever write? I received all my mail back from Santo Domingo. Do you have a new address? We haven't received your package from there anymore. I've written to you a few times already, please write back a short note too. Warm greetings to you, Your Richard and Frank.",
    detectedLanguage: "German",
    description: "The postcard features a collage of black and white photographs showcasing landmarks and scenes from Dresden. In the center, 'Grüße aus DRESDEN' (Greetings from DRESDEN) is written in white sans-serif font on a dark background. The images include a steamboat ('Weiße Flotte' - White Fleet) on a river, the Zwinger palace complex (several views, including a fountain and exterior), the 'Kulturpalast' (Culture Palace) with cars on a street in front, and the 'Goldener Reiter' (Golden Rider) statue.",
    words: ["May", "12", "1972", "Dear", "Bubu", "and", "family", "Why", "don't", "you", "ever", "write", "I", "received", "all", "my", "mail", "back", "from", "Santo", "Domingo", "Do", "you", "have", "a", "new", "address", "We", "haven't", "received", "your", "package", "from", "there", "anymore", "I've", "written", "to", "you", "a", "few", "times", "already", "please", "write", "back", "a", "short", "note", "too", "Warm", "greetings", "to", "you", "Your", "Richard", "and", "Frank"],
  },
  {
    id: "sample-standseilbahn",
    title: "Dresden Railway",
    location: "Dresden",
    language: "German",
    frontImage: require("@/assets/samples/standseilbahn_front.jpg"),
    backImage: require("@/assets/samples/standseilbahn_back.jpg"),
    originalText: "Sippych.\nEs ist mir endlich lieb wohl, andere Päckchen noch.\nHätte mir gern an der Goofi Böller Geschirr und Haustand was sinner hönsamm.\nDie ich hörte war einie wunderschön.\nOpa hat viel oder sind verheizt, kann kommen.\nGeht viel lieber hin zu mir, Sande...",
    translatedText: "Sippych.\nI am finally well pleased, still other packages.\nI would gladly have some Goofi crackers, dishes and household items, whatever is so cozy.\nThe one I heard about was a beautiful one.\nGrandpa has a lot or they are used up, he can come.\nIt is much better to come to me, Sande...",
    detectedLanguage: "German",
    description: "A black and white photograph of a steep hillside covered with numerous buildings and trees. A funicular railway track, supported by a large steel trestle, ascends diagonally up the slope, with two cars visible on the tracks. At the very top of the hill, a prominent, large building complex with a tower can be seen, resembling a castle or large estate. Faint text 'Dresden, Stand...' is visible in the bottom left corner.",
    words: ["Sippych.", "I", "am", "finally", "well", "pleased,", "still", "other", "packages.", "I", "would", "gladly", "have", "some", "Goofi", "crackers,", "dishes", "and", "household", "items,", "whatever", "is", "so", "cozy.", "The", "one", "I", "heard", "about", "was", "a", "beautiful", "one.", "Grandpa", "has", "a", "lot", "or", "they", "are", "used", "up,", "he", "can", "come.", "It", "is", "much", "better", "to", "come", "to", "me,", "Sande..."],
  },
  {
    id: "sample-neujahr",
    title: "New Year's Card",
    location: "Dresden",
    language: "German",
    frontImage: require("@/assets/samples/neujahr_front.jpg"),
    backImage: require("@/assets/samples/neujahr_back.jpg"),
    originalText: "29. 11. 83\nLieber Bruni,\nu. Familie!\nNach sehr lange Zeit\neinige herzliche Grüsse\naus dem Heimath\nmit der Hoffnung das\nes u. deiner Familie\ngesund geht\nu. gleichzeitig ein\nfrohes Weihnachten\nu. gesundes Neujahrs\nwünscht Euch\nOnkel Horst + T. domiz\nsowie meine Familie.\n\nEvtl. kannst Du mir\neinmal von diesem\nmeinen Eltern senden.\nliebe viel Richard\nnicht mehr da, aber\nfrank besuche ich ab + zu.",
    translatedText: "29. 11. 83\nDear Bruni,\nand family!\nAfter a very long time\nsome heartfelt greetings\nfrom home\nwith the hope that\nyou and your family\nare well\nand at the same time\nwish you\na Merry Christmas\nand a healthy New Year\nUncle Horst + T. Domiz\nas well as my family.\n\nPerhaps you can send me\none of these (or this one) to my parents.\nDear Richard\nis no longer there, but\nI visit Frank now and then.",
    detectedLanguage: "German",
    description: "The front of the postcard features a charming, whimsical illustration in an oval frame. A striped, orange cat with a white belly and red cheeks is climbing a tree-like structure that resembles a birch log. The log has black spots and is topped with a small brown cap and two red mushrooms. Green foliage branches out from the log. Two birds, one reddish-brown and one blue and yellow, are perched on the branches. A pretzel-like shape hangs from one branch. There are also a few colorful, stylized flowers and a smiling sun-like figure. At the bottom, in an arched banner, are the words \"PROSIT NEUJAHRS\" (Happy New Year).",
    words: ["29.", "11.", "83", "Dear", "Bruni,", "and", "family!", "After", "a", "very", "long", "time", "some", "heartfelt", "greetings", "from", "home", "with", "the", "hope", "that", "you", "and", "your", "family", "are", "well", "and", "at", "the", "same", "time", "wish", "you", "a", "Merry", "Christmas", "and", "a", "healthy", "New", "Year", "Uncle", "Horst", "+", "T.", "Domiz", "as", "well", "as", "my", "family.", "Perhaps", "you", "can", "send", "me", "one", "of", "these", "(or", "this", "one)", "to", "my", "parents.", "Dear", "Richard", "is", "no", "longer", "there,", "but", "I", "visit", "Frank", "now", "and", "then."],
  },
  {
    id: "sample-scouts",
    title: "Scout Camp 1934",
    location: "Germany",
    language: "German",
    frontImage: require("@/assets/samples/scouts_front.jpg"),
    backImage: require("@/assets/samples/scouts_back.jpg"),
    originalText: "Den lints! auf aufs\nGrüße; Stürm; Jungens; Eugen, Zeuber,\nPrisort; Heimann, Goop\nPrüfel; Grundlich; Dallfur, Zemuy;",
    translatedText: "To the left one! Up, up!\nGreetings; Stürm; Youngsters; Eugen, Zeuber,\nPrisort; Heimann, Goop\nPrüfel; Gründlich; Dallfur, Zemuy;",
    detectedLanguage: "de",
    description: "A black and white photograph showing eleven young boys or teenagers in uniform, standing in a line in a grassy field. They are wearing short-sleeved shirts, dark shorts, dark socks, and boots, with neckerchiefs or ties. Several large canvas tents are visible in the background, suggesting a camp setting. The overall scene depicts a youth group in an outdoor environment.",
    words: ["To", "the", "left", "one!", "Up,", "up!", "Greetings;", "Stürm;", "Youngsters;", "Eugen,", "Zeuber,", "Prisort;", "Heimann,", "Goop", "Prüfel;", "Gründlich;", "Dallfur,", "Zemuy;"],
    audioAsset: require("@/assets/samples/scouts_audio.mp3"),
    durationMs: 17897,
    wordTimings: scoutsTimings,
  },
  {
    id: "sample-deer",
    title: "Deer Park",
    location: "Germany",
    language: "German",
    frontImage: require("@/assets/samples/deer_front.jpg"),
    backImage: require("@/assets/samples/deer_back.jpg"),
    originalText: "Zur Erinnerung\nan Ferien 1934.\nHermann Moritzburg\nund\n6. Juni 1934.",
    translatedText: "In memory\nof vacation 1934.\nHermann Moritzburg\nand\nJune 6, 1934.",
    detectedLanguage: "de",
    description: "A black and white photograph shows a young boy, viewed from behind, standing next to a wooden post and looking at several deer. One deer with small antlers is close to the boy. Other deer are scattered in the foreground and mid-ground, some grazing. In the background, there is a dense forest of trees.",
    words: ["In", "memory", "of", "vacation", "1934.", "Hermann", "Moritzburg", "and", "June", "6,", "1934."],
    audioAsset: require("@/assets/samples/deer_audio.mp3"),
    durationMs: 9459,
    wordTimings: deerTimings,
  },
  {
    id: "sample-dresden-letter",
    title: "Dresden Letter 1980",
    location: "Dresden",
    language: "German",
    frontImage: require("@/assets/samples/christmas_front.jpg"),
    backImage: require("@/assets/samples/dresden_letter_back.jpg"),
    originalText: "Dresden, 28.11.80\nLieber Bubi u. Familie!\nWünscht Euch von Herzen Richard Franks Ragfcula u. Duni.\n\nDu erst möchte ich mal anfragen ob Ihr alle noch\nGesund seid. Uns geht es zum soweit noch gut. Nun ist\nja bald wieder Weihnachten das sind nun schon die 2\nohne meine Mütze, ich komme nicht darüber hinweg\nKann es nicht fassen. Gehe jeden Tag an Ihr Grab. Meine\nFreude am leben ist vorbei. Werde meiner Maisie wieder\neinen kleinen Weihnachtsbaum mit Kerzen auf Ihr\nGrab stellen. Wenn ich bei Ihr war, hab ich es\nwieder Ruhe. Habe sonst auch immer viel Arbeit\ngehe noch 3 Tage arbeiten, bin ja auch Rentner sonst\nwird es mir zu langweilig. Hans mit seiner\nFrau waren dieses Jahr auch in Dresden habe\nmich tüchtig gefreut. Hat Ihm auch gepasst.\nhaben schöne Fahrten gemacht, Streller Georg\nist auch gestorben der 92 Jahre.\n\nViele herzli. Grüsse\nSendet Euch Richard\n\nFrohe Weihnachten\nund viel Glück\nim neuen\nJahr",
    translatedText: "Dresden, 28.11.80\nDear Bubi and Family!\nRichard Franks Ragfcula and Duni wish you all the best from their hearts.\n\nFirst, I wanted to ask if you are all still healthy. We are still doing well so far. Soon it will be Christmas again, and this is already the second one without my wife. I can't get over it. I can't grasp it. I go to her grave every day. My joy in life is over. I will put a small Christmas tree with candles on her grave for my Maisie again. When I have been with her, I have peace again. Otherwise, I still have a lot of work; I will work for 3 more days. I am also a retiree, otherwise, I would get too bored. Hans and his wife were also in Dresden this year, I was very happy about it. It also suited him. We made nice trips. Streller Georg also passed away at 92 years old.\n\nMany warm greetings\nRichard sends you\n\nMerry Christmas\nand a Happy New Year",
    detectedLanguage: "German",
    description: "The postcard features a handwritten message on one side, dated Dresden, 28.11.80. The other side (front) has a festive greeting printed in an old-fashioned German script (Fraktur) on a plain white background, stating \"Frohe Weihnachten und viel Glück im neuen Jahr\" (Merry Christmas and a Happy New Year).",
    words: ["Dresden", "28.11.80", "Dear", "Bubi", "and", "Family!", "Richard", "Franks", "Ragfcula", "and", "Duni", "wish", "you", "all", "the", "best", "from", "their", "hearts.", "First,", "I", "wanted", "to", "ask", "if", "you", "are", "all", "still", "healthy.", "We", "are", "still", "doing", "well", "so", "far.", "Soon", "it", "will", "be", "Christmas", "again,", "and", "this", "is", "already", "the", "second", "one", "without", "my", "wife.", "I", "can't", "get", "over", "it.", "I", "can't", "grasp", "it.", "I", "go", "to", "her", "grave", "every", "day.", "My", "joy", "in", "life", "is", "over.", "I", "will", "put", "a", "small", "Christmas", "tree", "with", "candles", "on", "her", "grave", "for", "my", "Maisie", "again.", "When", "I", "have", "been", "with", "her,", "I", "have", "peace", "again.", "Otherwise,", "I", "still", "have", "a", "lot", "of", "work;", "I", "will", "work", "for", "3", "more", "days.", "I", "am", "also", "a", "retiree,", "otherwise,", "I", "would", "get", "too", "bored.", "Hans", "and", "his", "wife", "were", "also", "in", "Dresden", "this", "year,", "I", "was", "very", "happy", "about", "it.", "It", "also", "suited", "him.", "We", "made", "nice", "trips.", "Streller", "Georg", "also", "passed", "away", "at", "92", "years", "old.", "Many", "warm", "greetings", "Richard", "sends", "you", "Merry", "Christmas", "and", "a", "Happy", "New", "Year"],
  },
  {
    id: "sample-dresden-panorama",
    title: "Dresden Panorama",
    location: "Dresden",
    language: "German",
    frontImage: require("@/assets/samples/dresden_panorama_front.jpg"),
    backImage: require("@/assets/samples/dresden_panorama_back.jpg"),
    originalText: "Lieber Onkel Bubi, Tante Rita u. Kinder.\nMit großer Freude haben wir\nEuer Packet über Geneves Weih-\nnachten erhalten. Haben uns\nsehr gefreut. Hoffentlich seid Ihr\nalle noch gesund und auch\nden Wurstgewittern \"geht es noch\ngut.\" Jahren schon so drollig aus.\nViele Grüße über den großen Teich\nsenden Euch Frank, Mutti u. Vati.",
    translatedText: "Dear Uncle Bubi, Aunt Rita and children.\nWith great joy we have\nreceived your package over Geneves Christmas. We were\nvery happy. Hopefully you are\nall still healthy and also\nwith the \"sausage storms\" it's still going\nwell. Years already so funny.\nMany greetings across the big pond\nsend you Frank, Mom and Dad.",
    detectedLanguage: "de",
    description: "The front of the postcard features a black and white collage of images from Dresden, Germany. A large central image shows the ornate architecture of the Zwinger palace with fountains. Smaller inset images depict river views and other cityscapes. The word \"DRESDEN\" is prominently displayed in white letters on a black rectangle, and a coat of arms (a lion rampant with stripes) is visible in the bottom left corner.",
    words: ["Dear", "Uncle", "Bubi", "Aunt", "Rita", "and", "children", "With", "great", "joy", "we", "have", "received", "your", "package", "over", "Geneves", "Christmas", "We", "were", "very", "happy", "Hopefully", "you", "are", "all", "still", "healthy", "and", "also", "with", "the", "sausage", "storms", "it's", "still", "going", "well", "Years", "already", "so", "funny", "Many", "greetings", "across", "the", "big", "pond", "send", "you", "Frank", "Mom", "and", "Dad"],
  },
];
